### ISSUE TITLE
Blue-Pic server not starting in Bluemix

### ISSUE THREAD

**Issue by csantanapr** [IBM-Swift/BluePic#281] opened 2016-06-23 15:56 UTC
updated BluePic-Server/properties.json with openwhisk info

Then use both IBM Cloud Tool to deploy and it the stay as running, never started
Then login into Bluemix and restart App
Logs shows errors:
```
STG/0 Linking CHttpParser2016-06-23T11:50:58.928-0400
STG/0 /tmp/staged/app/Packages/Socket-0.5.20/Sources/Socket.swift:1798:42: error: use of undeclared type 'Data'2016-06-23T11:50:59.614-0400
STG/0 ^~~~2016-06-23T11:50:59.615-0400
STG/0 /tmp/staged/app/Packages/Socket-0.5.20/Sources/Socket.swift:1847:36: error: use of undeclared type 'Data'2016-06-23T11:50:59.615-0400
STG/0 data.append(self.readStorage as Data)2016-06-23T11:50:59.615-0400
STG/0 guard let str = NSString(data: data as Data, encoding: NSUTF8StringEncoding.rawValue)2016-06-23T11:50:59.615-0400
STG/0 ^~~~2016-06-23T11:50:59.615-0400
STG/0 /tmp/staged/app/Packages/SwiftyJSON-7.0.4/Source/SwiftyJSON.swift:840:38: error: use of undeclared type 'JSONSerialization'2016-06-23T11:50:59.756-0400
STG/0 public func rawData(options opt: JSONSerialization.WritingOptions = JSONSerialization.WritingOptions(rawValue: 0)) throws -> NSData {2016-06-23T11:50:59.756-0400
STG/0 ^~~~~~~~~~~~~~~~~2016-06-23T11:50:59.756-0400
STG/0 /tmp/staged/app/Packages/SwiftyJSON-7.0.4/Source/SwiftyJSON.swift:97:35: error: type 'String' has no member 'Encoding'2016-06-23T11:50:59.757-0400
STG/0 return string.data(using: String.Encoding.utf8).flatMap({JSON(data: $0)}) ?? JSON(NSNull())2016-06-23T11:50:59.757-0400
STG/0 ^~~~~~ ~~~~~~~~2016-06-23T11:50:59.757-0400
STG/0<unknown>:0: error: build had 2 command failures2016-06-23T11:51:06.787-0400
STG/0Staging failed: Buildpack compilation step failed2016-06-23T11:51:06.801-0400
STG/0swift-build: error: exit(1): /tmp/cache/swift-DEVELOPMENT-SNAPSHOT-2016-05-03-a/swift-DEVELOPMENT-SNAPSHOT-2016-05-03-a-ubuntu14.04/usr/bin/swift-build-tool -f /tmp/staged/app/.build/release.yaml2016-06-23T11:51:06.790-0400
API/10encountered error: App staging failed in the buildpack compile phase2016-06-23T11:51:07.060-0400
```

cc @triceam

**Comment by csantanapr** [comment] 2016-06-23 16:11
Try again putting properties.json back to initial state, and try again to deploy still errors

```
STG/0 Compile Cryptor2016-06-23T12:03:58.424-0400
STG/0 Compile SimpleLogger2016-06-23T12:03:58.425-0400
STG/0 Compile KituraTemplateEngine2016-06-23T12:03:58.427-0400
STG/0 Compile SwiftyJSON2016-06-23T12:03:58.428-0400
STG/0 Compile Socket2016-06-23T12:03:58.429-0400
STG/0 Compile LoggerAPI2016-06-23T12:03:58.431-0400
STG/0 Compile CHttpParser utils.c2016-06-23T12:03:58.737-0400
STG/0 Compile CHttpParser http_parser.c2016-06-23T12:03:58.874-0400
STG/0 Compile KituraSys2016-06-23T12:03:59.412-0400
STG/0 Compile HeliumLogger2016-06-23T12:04:00.250-0400
STG/0 /tmp/staged/app/Packages/SwiftyJSON-7.0.4/Source/SwiftyJSON.swift:840:38: error: use of undeclared type 'JSONSerialization'2016-06-23T12:04:00.857-0400
STG/0 public func rawData(options opt: JSONSerialization.WritingOptions = JSONSerialization.WritingOptions(rawValue: 0)) throws -> NSData {2016-06-23T12:04:00.857-0400
STG/0 return string.data(using: String.Encoding.utf8).flatMap({JSON(data: $0)}) ?? JSON(NSNull())2016-06-23T12:04:00.857-0400
STG/0 /tmp/staged/app/Packages/SwiftyJSON-7.0.4/Source/SwiftyJSON.swift:97:35: error: type 'String' has no member 'Encoding'2016-06-23T12:04:00.857-0400
STG/0 Linking CHttpParser2016-06-23T12:04:00.857-0400
STG/0 ^~~~~~ ~~~~~~~~2016-06-23T12:04:00.857-0400
STG/0 /tmp/staged/app/Packages/Socket-0.5.20/Sources/Socket.swift:1798:42: error: use of undeclared type 'Data'2016-06-23T12:04:01.722-0400
STG/0 /tmp/staged/app/Packages/Socket-0.5.20/Sources/Socket.swift:1847:36: error: use of undeclared type 'Data'2016-06-23T12:04:01.722-0400
STG/0 guard let str = NSString(data: data as Data, encoding: NSUTF8StringEncoding.rawValue)2016-06-23T12:04:01.722-0400
STG/0 ^~~~2016-06-23T12:04:01.722-0400
STG/0 data.append(self.readStorage as Data)2016-06-23T12:04:01.722-0400
STG/0 ^~~~2016-06-23T12:04:01.722-0400
STG/0<unknown>:0: error: build had 2 command failures2016-06-23T12:04:08.753-0400
STG/0swift-build: error: exit(1): /tmp/cache/swift-DEVELOPMENT-SNAPSHOT-2016-05-03-a/swift-DEVELOPMENT-SNAPSHOT-2016-05-03-a-ubuntu14.04/usr/bin/swift-build-tool -f /tmp/staged/app/.build/release.yaml2016-06-23T12:04:08.757-0400
STG/0Staging failed: Buildpack compilation step failed2016-06-23T12:04:08.768-0400
API/8encountered error: App staging failed in the buildpack compile phase
```

**Comment by rolivieri** [comment] 2016-06-23 16:28
@csantanapr Looks like you are having a compilation error. What I would suggest is to do a fresh clone of this repo (master branch) and compile the server code locally. Done that, then execute cf push from the root folder of this repo. Can you try that?

**Comment by rolivieri** [comment] 2016-06-28 14:52
@csantanapr Hello, did you try using the "Deploy to Bluemix" button on the master branch? That would help rule out if the issue is a bug in the BluePic code or somewhere else?

**Comment by csantanapr** [comment] 2016-06-29 01:56
Hi @rolivieri I just got a chance to try this again.
I tried the button "Deploy to Bluemix" it fails like this: "Repository cloning failed"
![image](https://cloud.githubusercontent.com/assets/1094878/16438146/11e8db8e-3d7b-11e6-8f2f-9ed5a80920b6.png)

**Comment by csantanapr** [comment] 2016-06-29 03:17
I was able to get the Server running locally and remotely by taking the latest code from master, then update `cloud_config.json` 

But clicking the Deploy button, and deploying to a different space `demo` failed like the picture above.

**Comment by dzcarter** [comment] 2016-07-06 19:20
I'm possibly having the same issue.

I am trying to get the sample BluePic project running from within the IBM Cloud Tools For Swift app. After I create the project, give a name and directory, it goes off to do its thing. It seems to create a project, but I get an error alert box saying "Error: You are not authorized to perform the requested action". The light beside the project immediately goes red. If I hit the restart button, it stays red and says Error in the ICT app.

Issue #1
Looking into the logs for the application in my bluemix console, I don't see much activity which is odd. I tried this yesterday and there were crash logs there. Turns out the app was never deployed. So I hit the deploy button in ICT and the logs show it's cloning and installing dependencies.

Issue #2
After the app is deployed and downloads/installs all of its dependencies, it crashes:
>App instance exited with guid b576761d-9241-485b-a635-10b1b2656731 payload: {"cc_partition"=>"default", "droplet"=>"b576761d-9241-485b-a635-10b1b2656731", "version"=>"a6c6f89c-6a20-4b22-8885-7df6f2b0fa74", "instance"=>"bcc74e9129dd41c3a030a922ab125876", "index"=>0, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"failed to accept connections within health check timeout", "crash_timestamp"=>1467832031}

After a couple minutes, it retries (I'm guessing this is ICT initiating the retry?). And there is a new warning and error not there in the previous attempt: 
>VERBOSE: init() Router.swift line 59 - Router initialized
>WARNING: init() Configuration.swift line 47 - Could not find 'cloud_config.json'.
>ERROR: Server main.swift line 75 - Oops, something went wrong... Server did not start!

Following that, I get the same crash error as above.

**Comment by tfrank64** [comment] 2016-07-07 15:32
@dzcarter I have been testing more with the ICT tool and I experience some of the issues you mentioned so I'm looking into why.

**Comment by tfrank64** [comment] 2016-07-07 16:08
@csantanapr @dzcarter It seems like these issues are definitely related.

First, the "You are not authorized to perform the requested action" error might be due to the weather service changing some of its configuration and it should be fixed in the next release of ICT.

Second, I also was not able to use the "deploy to bluemix" button. I even had a failure pushing services from the command line with cloud-foundry. But on the command line, I got the following error:

> Server error, status code: 502, error code: 10001, message: Service broker error: {"description"=>"Object Storage create request not allowed. The Free plan is limited to one Object Storage service instance per organization."}

So I believe it is that or something like it, a service limitation issue, that is causing most BluePic deploying issues. There will be more checks for these limitations in the next ICT release. For any future issues you think ICT might be responsible for, check out this [link](https://developer.ibm.com/answers/topics/cloud-tools-for-swift.html) or give [feedback](http://www.surveygizmo.com/s3/2772127/Feedback).

I'm still looking into the `Configuration.swift line 47 - Could not find 'cloud_config.json'` issue.

**Comment by tfrank64** [comment] 2016-07-07 16:58
I am still able to create services with the `services.sh` script in BluePic and I can `cf push` from command line without problems. That is an option for now until we get a newer version of ICT.

**Comment by tfrank64** [comment] 2016-07-08 23:04
@csantanapr @dzcarter Please try out the latest version of IBM Cloud Tools `Version 1.0.1.6 (31)`
I just tried it and it worked great with BluePic. It should resolve all your BluePic and ICT related issues.

**Comment by rolivieri** [comment] 2016-07-13 15:50
Closing this issue since @tfrank64 has confirmed the ICT tool has been updated to address the problem you guys were facing. If you guys run into new issues in the future with the ICT tool, please feel free to reach out to the ICT team at https://developer.ibm.com/answers/topics/cloud-tools-for-swift.html.

**Closed by rolivieri** 2016-07-13 15:50 UTC
Labels: bug
